name: .NetFramework.CI

on:
  push:
    branches:    
      - master
        
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: list out the files  
      run : ls
    - uses: azure/webapps-deploy@v1
      with:
        creds: ${{ secrets.azureWebAppPublishProfile }}
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild
      run: msbuild SeleniumNUnitParam/SeleniumNUnitParam/SeleniumNUnitParam.csproj -p:Configuration=Release
    - name: list out the files 
      working-directory: SeleniumNUnitParam
      run : ls
    - name: create a AppDir
