name: NetFrameWork.CI

on: 	
  push:	
    branches:	
      - master
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v1 
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: setup nuget 
      run : nuget restore SeleniumNUnitParam.sln
    - name: Build with MSBuild
      run: msbuild SeleniumNUnitParam.sln -p:Configuration=Release
    
