name: NetFrameWork.CI

on: 	
  push:	
    branches:	
      - master
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v1 
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: setup nuget 
      run : nuget restore SeleniumNUnitParam.sln
    - name: create a session 
      run : |
          WebClient = New-Object System.Net.WebClient
          WebClient.Credentials = New-Object System.Net.NetworkCredential(mulintisanthoshkumar, r]J9Lp9u]ia__3r)
          WebClient.UploadFile(C:\SeleniumNUnitParam\*, \\35.188.202.141\
