name: NetFrameWork.CI

on: 	
  push:	
    branches:	
      - master
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v1 
    - name: Setup MSBuild.exe
      run : ls 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin'
    - name: setup nuget 
      run : nuget restore SeleniumNUnitParam.sln
    - name: add a trusted host 
      env:
        USERNAME : ${{ secrets.USERNAME }}
        PASSWORD : ${{ secrets.PASSWORD }} 
      run : |
           $Username = 'mulintisanthoshkumar'
           $Password = 'r]J9Lp9u]ia__3r'
           $pass = ConvertTo-SecureString -AsPlainText $Password -Force
           $SecureString = $pass
           $MySecureCreds = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $Username,$SecureString			
           winrm set winrm/config/client '@{TrustedHosts="35.188.202.141"}'         
           $Session = New-PSSession -ComputerName "35.188.202.141" -Credential $MySecureCreds  
           Copy-Item "D:\a\SeleniumNUnitParam\SeleniumNUnitParam\*" -Destination "C:\Users" -ToSession $Session -Recurse
 
