name: .NetFramework.CI

on:
  push:
    branches:    
      - master
        
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: list out the files  
      run : ls
    - name: create a AppDir
      run : New-Item -ItemType directory -Path "C:\AppDir"
    - name: add a trusted host and CopyFiles@2 the application server
      run : |
           $Username = 'mulintisanthoshkumar'
           $Password = 'oKllPV-@ha)6u?n'
           $pass = ConvertTo-SecureString -AsPlainText $Password -Force
           $SecureString = $pass
           $MySecureCreds = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $Username,$SecureString			
           winrm set winrm/config/client '@{TrustedHosts="35.238.74.183"}'         
           $Session = New-PSSession -ComputerName "35.238.74.183" -Credential $MySecureCreds  
           Copy-Item "D:\a\SeleniumNUnitParam\SeleniumNUnitParam\*" -Destination "C:\" -ToSession $Session -Recurse
