name: APPSERVERDEPLOYMENT
on: 
 push:
    branches:
     - 'master'
     - 'devlope'
    
  
jobs:
  build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: windows-latest
    steps:
    - name: 'Checkout Github Action' 
      with:
        ref: master
      uses: actions/checkout@master
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: list out the files 
      run: ls
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    
    - run: |
        az webapp list --query "[?state=='Running']"
    - uses: azure/webapps-deploy@v1
      with: 
        app-name: santhosh321
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        
        
  build-and-deploy-server:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: self-hosted
    steps:
    - name: 'Checkout Github Action' 
      with:
        ref: devlope
      uses: actions/checkout@master
    - name: update the nuget  
      run: |
         cd C:\actions-runner\_work\_tool\nuget\latest\x64
         nuget restore C:\actions-runner\_work\dotnet-framework-docker\dotnet-framework-docker\samples\aspnetapp\aspnetapp.sln 
      shell: cmd
    - name: MSBuild
      run: |  
          cd C:\actions-runner\MSBuild\Microsoft\Bin
          msbuild C:\actions-runner\_work\dotnet-framework-docker\dotnet-framework-docker\samples\aspnetapp\aspnetapp\aspnetapp.csproj /p:Configuration=Release -p:OutDir=c:\santhoshkumaar
      shell: cmd        

  DEPLOYDBTOSQLSERVER2:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop/'
    runs-on: self-hosted
    steps: 
     - name: download build artifacts
       uses: actions/checkout@v1
     - name: update database schema using dacpac deploy action       
       working-directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\SQL\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150
       run: sqlpackage.exe /SourceFile:"C:\actions-runner\_work\DeployDB\DeployDB\ContosoRetailDW_1.dacpac" /Action:Publish /TargetServerName:"35.224.110.251\MYSQLINSTANCE" /TargetDatabaseName:"ContosoRetailDW" /TargetUser:${{ secrets.USERNAME }} /TargetPassword:${{ secrets.PASSWORD }}
       shell: cmd

