name: DEPLOYDBTOSQLSERVER
on:
  push:
    branches:    
      - master       
jobs:
  build:
    runs-on: windows-latest
    steps:
     - name: download build artifacts
       uses: actions/checkout@v1
     - name: Azure Login
     - uses: Azure/login@v1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
