name: NetFrameWork.CI

on: 	
  push:	
    branches:	
      - master
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v1 
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: setup nuget 
      run : nuget restore SeleniumNUnitParam.sln
    - name: create a session 
      env:
        USERNAME : ${{ secrets.USERNAME }}
        PASSWORD : ${{ secrets.PASSWORD }} 
      run : |
         $password = ConvertTo-SecureString "r]J9Lp9u]ia__3r" -AsPlainText -Force
         $Cred = New-Object System.Management.Automation.PSCredential (“mulintisanthoshkumar”, $password)
         $sess = New-PSSession -Credential $cred -ComputerName 35.188.202.141
         
